apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment-m10
  namespace: mauricio-toapanta-dev
  labels:
    app: mi-app10
    areanegocio: tecnologia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app10
  template:
    metadata:
      labels:
        app: mi-app10
    spec:
      containers:
        - name: contenedor-principal
          image: mauriciotoapanta/hola-mundo-clase-86-10:build-{{ tag }}  # <-- Reemplaza con la imagen que quieras usar
          #image: image-registry.openshift-image-registry.svc:5000/mauricio-toapanta-dev/openshift-1-git-s2i  # <-- Reemplaza con la imagen que quieras usar
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "800Mi"
            limits:
              cpu: "1000m"
              memory: "1500Mi"
          envFrom:
            - configMapRef:
                name: mi-configmap-m10
            - secretRef:
                name: mi-secret-m10
          startupProbe:
            httpGet:
              path: /startup
              port: 3000
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-m10
  namespace: mauricio-toapanta-dev  # Asegúrate de que coincida con tu Deployment
spec:
  selector:
    app: mi-app10  # Debe coincidir con las labels del Deployment
  ports:
    - protocol: TCP
      port: 4000        # Puerto del Service
      targetPort: 3000  # Puerto del contenedor
  type: ClusterIP     # Cambia a NodePort o LoadBalancer si quieres acceso externo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-configmap-m10
  namespace: mauricio-toapanta-dev
data:
  DATABASE: "192.168.1.1"

---
apiVersion: v1
kind: Secret
metadata:
  name: mi-secret-m10
  namespace: mauricio-toapanta-dev
type: Opaque
data:
  PASSWORD: aG9sYQ==
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mi-hpa10
  namespace: mauricio-toapanta-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: mi-deployment-m10
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-pvc-m10a
  namespace: mauricio-toapanta-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3